In [1]:
import numpy as np
import pandas as pd
df=pd.read_parquet('ProjectRawData.parquet', engine='fastparquet')
author_counts=df["author.name"].value_counts()
author_counts
data={"User":author_counts.index,"Count":author_counts}
my_df=pd.DataFrame(data)
my_df["index_num"]=np.arange(len(my_df))
my_df["isTop-10"]=np.where(my_df["index_num"]<=10,True,False)
my_df["isTop-50"]=np.where(my_df["index_num"]<=50,True,False)
my_df["isTop-100"]=np.where(my_df["index_num"]<=100,True,False)

In [2]:
my_df

,User,Count,index_num,isTop-10,isTop-50,isTop-100
Deleted User,Deleted User,56679,0,True,True,True
Trogdor,Trogdor,44448,1,True,True,True
javicha,javicha,29978,2,True,True,True
nola,nola,22579,3,True,True,True
Bdawg13,Bdawg13,21123,4,True,True,True
...,...,...,...,...,...,...
Van Whoa,Van Whoa,1,2494,False,False,False
RabidBeaver,RabidBeaver,1,2495,False,False,False
beanooo,beanooo,1,2496,False,False,False
Tinfoilhatsforu,Tinfoilhatsforu,1,2497,False,False,False
aljnbtwn,aljnbtwn,1,2498,False,False,False

In [3]:
df

,id,type,timestamp,timestampEdited,callEndedTimestamp,isPinned,content,attachments,embeds,stickers,...,author.avatarUrl,author.color,author.discriminator,author.id,author.isBot,author.name,author.nickname,reference.channelId,reference.guildId,reference.messageId
0,700077399949312100,Default,2020-04-15T20:17:38.957+00:00,None,NaN,False,ðŸ˜¢,None,None,None,...,https://cdn.discordapp.com/avatars/29430110543...,None,9806,294301105439899649,0.0,amnesia,amnesia,None,None,None
1,700077403107622912,Default,2020-04-15T20:17:39.71+00:00,None,NaN,False,Lol,None,None,None,...,https://cdn.discordapp.com/avatars/39396481942...,None,1473,393964819423952927,0.0,Sunshine State,Sunshine State,None,None,None
2,700077470225006592,Default,2020-04-15T20:17:55.712+00:00,None,NaN,False,He truly did nuke it,None,None,None,...,https://cdn.discordapp.com/avatars/39396481942...,None,1473,393964819423952927,0.0,Sunshine State,Sunshine State,None,None,None
3,700077513120022618,Default,2020-04-15T20:18:05.939+00:00,None,NaN,False,"New phone, who dis?",None,None,None,...,https://cdn.discordapp.com/embed/avatars/2.png,None,8507,367331325717250048,0.0,bandb2013,bandb2013,None,None,None
4,700077565116940369,Default,2020-04-15T20:18:18.336+00:00,None,NaN,False,https://tenor.com/view/jeff-goldblum-jurassic-...,None,None,None,...,https://cdn.discordapp.com/avatars/29430110543...,None,9806,294301105439899649,0.0,amnesia,amnesia,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492461,1030633910004101140,Default,2022-10-15T00:11:12.397+00:00,None,NaN,False,"INPX close above 6.50, watcher early AM on Mon...",None,None,None,...,https://cdn.discordapp.com/avatars/99473797558...,#FF8514,1415,994737975588032654,0.0,Fresh Prints,Fresh Prints,None,None,None
492462,1030922122178084954,Default,2022-10-15T19:16:27.534+00:00,None,NaN,False,RMED will be 1000 better,None,None,None,...,https://cdn.discordapp.com/avatars/99861048509...,#05FF00,9856,998610485094125588,0.0,MrZackMorris,MrZackMorris,None,None,None
492463,1030922250150490164,Default,2022-10-15T19:16:58.045+00:00,None,NaN,False,Btw Iâ€™m eating up the float with my foreign ac...,None,None,None,...,https://cdn.discordapp.com/avatars/99861048509...,#05FF00,9856,998610485094125588,0.0,MrZackMorris,MrZackMorris,None,None,None
492464,1031291016499712040,Default,2022-10-16T19:42:18.794+00:00,None,NaN,False,Happy Sunday y'all.,None,None,None,...,https://cdn.discordapp.com/avatars/99473797558...,#FF8514,1415,994737975588032654,0.0,Fresh Prints,Fresh Prints,None,None,None
492465,1031293066625175663,Reply,2022-10-16T19:50:27.582+00:00,None,NaN,False,https://tenor.com/view/friends-joey-chandler-p...,None,None,None,...,https://cdn.discordapp.com/avatars/22710023514...,#4894FF,8283,227100235145412619,0.0,Ry,Ry,700077347251945472,428232997737594901,1031291016499712040

In [5]:
for_merege=pd.DataFrame(my_df["User"],my_df["isTop-10"],my_df["isTop-50"],my_df["isTop-100"])

In [6]:
for_merge

NameError: name 'for_merge' is not defined

In [7]:
for_merege

isTop-50,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
isTop-10,,,,,,,,,,,,,,,,,,,,,
True,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
True,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
True,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
True,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
True,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
False,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
False,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
False,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
False,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
False,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [8]:
del for_merege

In [9]:
for_merege

NameError: name 'for_merege' is not defined

In [10]:
for_merge = my_df[['User','isTop-10','isTop-50','isTop-100']].copy()

In [11]:
for_merge

                            User  isTop-10  isTop-50  isTop-100
Deleted User        Deleted User      True      True       True
Trogdor                  Trogdor      True      True       True
javicha                  javicha      True      True       True
nola                        nola      True      True       True
Bdawg13                  Bdawg13      True      True       True
...                          ...       ...       ...        ...
Van Whoa                Van Whoa     False     False      False
RabidBeaver          RabidBeaver     False     False      False
beanooo                  beanooo     False     False      False
Tinfoilhatsforu  Tinfoilhatsforu     False     False      False
aljnbtwn                aljnbtwn     False     False      False

[2499 rows x 4 columns]

In [12]:
for_merge.rename(columns={'User':'author.name'})

                     author.name  isTop-10  isTop-50  isTop-100
Deleted User        Deleted User      True      True       True
Trogdor                  Trogdor      True      True       True
javicha                  javicha      True      True       True
nola                        nola      True      True       True
Bdawg13                  Bdawg13      True      True       True
...                          ...       ...       ...        ...
Van Whoa                Van Whoa     False     False      False
RabidBeaver          RabidBeaver     False     False      False
beanooo                  beanooo     False     False      False
Tinfoilhatsforu  Tinfoilhatsforu     False     False      False
aljnbtwn                aljnbtwn     False     False      False

[2499 rows x 4 columns]

In [15]:
result_df=pd.merge(left=df,right=for_merge,left_on="author.name",right_on="author.name")

KeyError: 'author.name'

In [16]:
result_df=pd.merge(left=df,right=for_merge,left_on="author.name",right_on="author.name")

KeyError: 'author.name'

In [17]:
df

,id,type,timestamp,timestampEdited,callEndedTimestamp,isPinned,content,attachments,embeds,stickers,...,author.avatarUrl,author.color,author.discriminator,author.id,author.isBot,author.name,author.nickname,reference.channelId,reference.guildId,reference.messageId
0,700077399949312100,Default,2020-04-15T20:17:38.957+00:00,None,NaN,False,ðŸ˜¢,None,None,None,...,https://cdn.discordapp.com/avatars/29430110543...,None,9806,294301105439899649,0.0,amnesia,amnesia,None,None,None
1,700077403107622912,Default,2020-04-15T20:17:39.71+00:00,None,NaN,False,Lol,None,None,None,...,https://cdn.discordapp.com/avatars/39396481942...,None,1473,393964819423952927,0.0,Sunshine State,Sunshine State,None,None,None
2,700077470225006592,Default,2020-04-15T20:17:55.712+00:00,None,NaN,False,He truly did nuke it,None,None,None,...,https://cdn.discordapp.com/avatars/39396481942...,None,1473,393964819423952927,0.0,Sunshine State,Sunshine State,None,None,None
3,700077513120022618,Default,2020-04-15T20:18:05.939+00:00,None,NaN,False,"New phone, who dis?",None,None,None,...,https://cdn.discordapp.com/embed/avatars/2.png,None,8507,367331325717250048,0.0,bandb2013,bandb2013,None,None,None
4,700077565116940369,Default,2020-04-15T20:18:18.336+00:00,None,NaN,False,https://tenor.com/view/jeff-goldblum-jurassic-...,None,None,None,...,https://cdn.discordapp.com/avatars/29430110543...,None,9806,294301105439899649,0.0,amnesia,amnesia,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492461,1030633910004101140,Default,2022-10-15T00:11:12.397+00:00,None,NaN,False,"INPX close above 6.50, watcher early AM on Mon...",None,None,None,...,https://cdn.discordapp.com/avatars/99473797558...,#FF8514,1415,994737975588032654,0.0,Fresh Prints,Fresh Prints,None,None,None
492462,1030922122178084954,Default,2022-10-15T19:16:27.534+00:00,None,NaN,False,RMED will be 1000 better,None,None,None,...,https://cdn.discordapp.com/avatars/99861048509...,#05FF00,9856,998610485094125588,0.0,MrZackMorris,MrZackMorris,None,None,None
492463,1030922250150490164,Default,2022-10-15T19:16:58.045+00:00,None,NaN,False,Btw Iâ€™m eating up the float with my foreign ac...,None,None,None,...,https://cdn.discordapp.com/avatars/99861048509...,#05FF00,9856,998610485094125588,0.0,MrZackMorris,MrZackMorris,None,None,None
492464,1031291016499712040,Default,2022-10-16T19:42:18.794+00:00,None,NaN,False,Happy Sunday y'all.,None,None,None,...,https://cdn.discordapp.com/avatars/99473797558...,#FF8514,1415,994737975588032654,0.0,Fresh Prints,Fresh Prints,None,None,None
492465,1031293066625175663,Reply,2022-10-16T19:50:27.582+00:00,None,NaN,False,https://tenor.com/view/friends-joey-chandler-p...,None,None,None,...,https://cdn.discordapp.com/avatars/22710023514...,#4894FF,8283,227100235145412619,0.0,Ry,Ry,700077347251945472,428232997737594901,1031291016499712040

In [18]:
for_merge

                            User  isTop-10  isTop-50  isTop-100
Deleted User        Deleted User      True      True       True
Trogdor                  Trogdor      True      True       True
javicha                  javicha      True      True       True
nola                        nola      True      True       True
Bdawg13                  Bdawg13      True      True       True
...                          ...       ...       ...        ...
Van Whoa                Van Whoa     False     False      False
RabidBeaver          RabidBeaver     False     False      False
beanooo                  beanooo     False     False      False
Tinfoilhatsforu  Tinfoilhatsforu     False     False      False
aljnbtwn                aljnbtwn     False     False      False

[2499 rows x 4 columns]

In [19]:
result_df=pd.merge(left=df,right=for_merge,left_on="author.name",right_on="user")

KeyError: 'user'

In [20]:
test={for_merge["user"]:for_merge["isTop-10"]}

KeyError: 'user'

In [21]:
fore_merge

NameError: name 'fore_merge' is not defined

In [22]:
for_merge

                            User  isTop-10  isTop-50  isTop-100
Deleted User        Deleted User      True      True       True
Trogdor                  Trogdor      True      True       True
javicha                  javicha      True      True       True
nola                        nola      True      True       True
Bdawg13                  Bdawg13      True      True       True
...                          ...       ...       ...        ...
Van Whoa                Van Whoa     False     False      False
RabidBeaver          RabidBeaver     False     False      False
beanooo                  beanooo     False     False      False
Tinfoilhatsforu  Tinfoilhatsforu     False     False      False
aljnbtwn                aljnbtwn     False     False      False

[2499 rows x 4 columns]

In [ ]:
result_df=pd.merge(left=df,right=for_merge,left_on="author.name",right_on="author.name")

In [24]:
for_merge.rename(columns={"User":"author.name"},inplace=True)

In [25]:
for_merge

                     author.name  isTop-10  isTop-50  isTop-100
Deleted User        Deleted User      True      True       True
Trogdor                  Trogdor      True      True       True
javicha                  javicha      True      True       True
nola                        nola      True      True       True
Bdawg13                  Bdawg13      True      True       True
...                          ...       ...       ...        ...
Van Whoa                Van Whoa     False     False      False
RabidBeaver          RabidBeaver     False     False      False
beanooo                  beanooo     False     False      False
Tinfoilhatsforu  Tinfoilhatsforu     False     False      False
aljnbtwn                aljnbtwn     False     False      False

[2499 rows x 4 columns]

In [26]:
result_df=pd.merge(left=df,right=for_merge,left_on="author.name",right_on="author.name")

In [27]:
result_df

,id,type,timestamp,timestampEdited,callEndedTimestamp,isPinned,content,attachments,embeds,stickers,...,author.id,author.isBot,author.name,author.nickname,reference.channelId,reference.guildId,reference.messageId,isTop-10,isTop-50,isTop-100
0,700077399949312100,Default,2020-04-15T20:17:38.957+00:00,None,NaN,False,ðŸ˜¢,None,None,None,...,294301105439899649,0.0,amnesia,amnesia,None,None,None,False,False,False
1,700077565116940369,Default,2020-04-15T20:18:18.336+00:00,None,NaN,False,https://tenor.com/view/jeff-goldblum-jurassic-...,None,None,None,...,294301105439899649,0.0,amnesia,amnesia,None,None,None,False,False,False
2,700086890266886274,Default,2020-04-15T20:55:21.625+00:00,None,NaN,False,Great now Chicago Look away is stuck in my head,None,None,None,...,294301105439899649,0.0,amnesia,amnesia,None,None,None,False,False,False
3,700087143036485683,Default,2020-04-15T20:56:21.89+00:00,None,NaN,False,"â€œIf thereâ€™s a fight on chat someday, and you d...",None,None,None,...,294301105439899649,0.0,amnesia,amnesia,None,None,None,False,False,False
4,700377058437628044,Default,2020-04-16T16:08:23.108+00:00,None,NaN,False,@ðŸ’°âš”CAPOâš”ðŸ’° almost got a bat signal forming,None,None,None,...,294301105439899649,0.0,amnesia,amnesia,None,None,None,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492461,1030518806692507700,Default,2022-10-14T16:33:49.629+00:00,None,NaN,False,Halt time: 12:33:39PM\nEst Resume: 12:38:39PM,None,None,None,...,700494469967118430,1.0,TOP HALTED on Volatility,Atlas Trading,None,None,None,False,False,False
492462,1030523877681549322,Default,2022-10-14T16:53:58.647+00:00,None,NaN,False,Halt time: 12:53:34PM\nEst Resume: 12:58:34PM,None,None,None,...,700494469967118430,1.0,TOP HALTED on Volatility,Atlas Trading,None,None,None,False,False,False
492463,1030526903951577189,Default,2022-10-14T17:06:00.166+00:00,None,NaN,False,Halt time: 1:05:39PM\nEst Resume: 1:10:39PM,None,None,None,...,700494469967118430,1.0,TOP HALTED on Volatility,Atlas Trading,None,None,None,False,False,False
492464,1030542772979122197,Default,2022-10-14T18:09:03.637+00:00,None,NaN,False,Halt time: 2:08:11PM\nEst Resume: 2:13:11PM,None,None,None,...,700494469967118430,1.0,ALF HALTED on Volatility,Atlas Trading,None,None,None,False,False,False
492465,1030544139093287074,Default,2022-10-14T18:14:29.344+00:00,None,NaN,False,Halt time: 2:13:35PM\nEst Resume: 2:18:35PM,None,None,None,...,700494469967118430,1.0,ALF HALTED on Volatility,Atlas Trading,None,None,None,False,False,False

In [28]:
result_df.to_parquet('AuthorNameTop10_50_100.parquet')